Groq Llama 3.1
mckaywrigley/chatbot-ui pull request #1817
Opened 2024-07-23 16:30 UTC by murillocamargo

Added new Llama 3.1 model via Groq.

But getting this error message when trying to chat. Does this mean it's not yet available via API or something?

![image](https://github.com/user-attachments/assets/ad9a6270-d15e-40eb-a02c-1716f2cb2695)

2024-07-24 05:09 UTC, PixelVerseIT commented
> Early API access to Llama 3.1 405B is currently only available to paying customers - stay tuned for general availability. During preview launch, we are limiting all 3.1 models to max_tokens of 8k and 405b to 16k input tokens: https://console.groq.com/docs/models

![image](https://github.com/user-attachments/assets/8a1d3ce9-0327-44eb-9c46-bab08054827b)

2024-08-25 19:06 UTC, faraday commented on lib/build-prompt.ts
> -    rawParts.push({type: 'text', text: message.content})
Why do you touch Google Gemini code sections with a PR that addresses Groq Llama 3.1 ?

2024-08-25 19:06 UTC, faraday commented on lib/build-prompt.ts
> +  if (payload.chatSettings.model === "gemini-pro-vision") {
These look like automatic formatting changes with disturbs the focus of the PR here.

2024-08-25 19:06 UTC, faraday commented on supabase/types.ts
> +export interface Database {
It's best not to touch supabase related sections needlessly.

2024-08-25 19:08 UTC, faraday requested changes
I'd leave out the parts unrelated to Groq Llama 3.1

2025-05-18 22:40 UTC, closed without merging